<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="schedule">
    <label><?php __('Schedule your current order in the future')?></label>
    <button type="submit" title="Add to Cart" class="action tocart primary">
        <span><?php __('Schedule Order')?></span>
    </button>
    <div id="callendar-schedule">
        <input type="text" class="input-text required-entry" id="calendar_inputField" name="calendar_inputField" aria-required="true" >
        <script>
            require([
                "jquery",
                "mage/calendar"
            ], function($){
                var min = new Date(),
                    max = new Date();
                min.setDate(min.getDate() + 3);
                max.setDate(max.getDate() + 90);
                $("#calendar_inputField").calendar({
                    buttonText: "<?php echo __('Select Date') ?>",
                    minDate: min,
                    maxDate: max,
                    disableFunc: function (date) {
                        var day = date.getDay();
                        if (day==6 || day==7) {
                            return true;
                        }
                    }
                })
            });
        </script>
    </div>
</div>
<div class="actions">
    <?php  $_order = $block->getOrder() ?>

    <?php if ($this->helper('Magento\Sales\Helper\Reorder')->canReorder($_order->getEntityId())) : ?>
        <a href="#" data-post='<?php /* @escapeNotVerified */ echo
        $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
            ->getPostData($block->getReorderUrl($_order))
        ?>' class="action order">
            <span><?= /* @escapeNotVerified */ __('Reorder') ?></span>
        </a>
    <?php endif ?>
    <a class="action print"
       href="<?= /* @escapeNotVerified */ $block->getPrintUrl($_order) ?>"
       onclick="this.target='_blank';">
        <span><?= /* @escapeNotVerified */ __('Print Order') ?></span>
    </a>
    <?= $block->getChildHtml() ?>
</div>
