<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<style>
    .schedule-label{
        color: #f2703e;
    }
    #callendar-schedule{
        float:left;
    }
    .schedule{
        display: none;
        min-height: 40px;
        clear: left;
    }
    #order-schedule{
        margin-bottom: 5px;
        border-bottom: 1px solid #f2703e;
    }
</style>
<?php  $_order = $block->getOrder() ?>
<form id="order-schedule" action="<?php echo $block->getUrl('appointment/set/schedule')?>">
    <p><label class="schedule-label"><strong><?php echo __('Click here to schedule your Reorder')?></strong></label></p>
    <script>
        require([
            "jquery"
        ], function($){
            $(document).on('click', '.schedule-label', function(){
                $('.schedule').slideToggle(500);
            });
        });
    </script>
    <div class="schedule">

        <div id="callendar-schedule">
            <input type="hidden" class="input-text" id="schedule_order_id" name="order_id" value="<?php echo $_order->getId()?>" aria-required="true" >
            <input type="text" placeholder="Click to select date" class="input-text required-entry" id="calendar_inputField" name="calendar_inputField" aria-required="true" >
            <script>
                require([
                    "jquery",
                    "mage/calendar"
                ], function($){
                    var min = new Date(),
                        max = new Date();
                    min.setDate(min.getDate() + 3);
                    max.setDate(max.getDate() + 90);
                    $("#calendar_inputField").calendar({
                        buttonText: "<?php echo __('Select Date') ?>",
                        minDate: min,
                        maxDate: max,
                        disableFunc: function (date) {
                            var day = date.getDay();
                            if (day==1 || day==7) {
                                return true;
                            }
                        }
                    })
                });
            </script>
        </div>
        <button id="schedule-order" type="submit" title="Schedule Reorder" class="action tocart primary">
            <span><?php echo __('Schedule Reorder')?></span>
        </button>

    </div>
</form>
<div class="actions">
    <?php if ($this->helper('Magento\Sales\Helper\Reorder')->canReorder($_order->getEntityId())) : ?>
        <a href="#" data-post='<?php /* @escapeNotVerified */ echo
        $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
            ->getPostData($block->getReorderUrl($_order))
        ?>' class="action order">
            <span><?= /* @escapeNotVerified */ __('Reorder Now') ?></span>
        </a>
    <?php endif ?>
    <a class="action print"
       href="<?= /* @escapeNotVerified */ $block->getPrintUrl($_order) ?>"
       onclick="this.target='_blank';">
        <span><?= /* @escapeNotVerified */ __('Print Order') ?></span>
    </a>
    <?= $block->getChildHtml() ?>
</div>
