<?php
    $scheduledOrders = $block->getScheduledOrders();
?>
<style>
    .list-schedules thead td, .notice span{
        color: #f48256;
        font-weight: 600;
    }
    .notice{
        font-size: 11px;
        font-style: italic;
    }
</style>
<?php if($scheduledOrders->count()):?>
    <table class="list-schedules">
        <thead>
            <tr>
                <td><?php echo __('Created At') ?></td>
                <td><?php echo __('Order Next Date') ?></td>
                <td><?php echo __('Order No.') ?></td>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($scheduledOrders as $schedule):?>
            <tr>
                <td><?php echo $schedule->getCreatedAt()?></td>
                <td><?php echo $schedule->getNextDate()?></td>
                <td><a href="<?php echo $block->getUrl('/sales/order/view/order_id' . $schedule->getOrderId())?>"><?php echo $schedule->getOrderIncrementId()?></a></td>
            </tr>
        <?php endforeach;?>
        </tbody>
    </table>
    <br/>
    <p class="notice"><span>*</span><?php echo __('You will receive an email notification 48 hours before reordering your scheduled order')?></p>
<?php else:?>
    <p><?php echo __('You have no scheduled orders')?></p>
<?php endif;?>
